# Example 1. PLA with Scikit-learn 
---
1\. Import Iris datasets and modules

In [1]:
from sklearn import datasets
import numpy as np

In [2]:
iris = datasets.load_iris()
#print iris

2\. Split data

In [3]:
X = iris.data[:, [2,3]]
y = iris.target
np.unique(y)

array([0, 1, 2])

In [4]:
# See https://github.com/udacity/machine-learning/issues/202
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=0 )

3\. Standardization

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

4\. Use Perceptron

In [8]:
from sklearn.linear_model import Perceptron

In [9]:
ppn = Perceptron(n_iter=40, eta0=0.1, random_state=0, verbose=0)
ppn.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, eta0=0.1, fit_intercept=True,
      n_iter=40, n_jobs=1, penalty=None, random_state=0, shuffle=True,
      verbose=0, warm_start=False)

In [10]:
y_pred = ppn.predict(X_test_std)
print 'Misclassified sample: %d'%( (y_test != y_pred).sum() )

Misclassified sample: 4


In [11]:
#help(Perceptron)
#ppn.get_params()

In [12]:
from sklearn.metrics import accuracy_score
print 'Accuracy: %f' % accuracy_score(y_test, y_pred)
print 'Accuracy: %f' % ppn.score(X_test_std, y_test)

Accuracy: 0.911111
Accuracy: 0.911111


In [13]:
# W1, W2 for X1, X2 for 3 class
ppn.coef_

array([[-0.14874662, -0.11229737],
       [ 0.22431308, -0.20230671],
       [ 0.50351128,  0.28717266]])

In [14]:
# W0 for 3 class
ppn.intercept_

array([-0.1, -0.1, -0.5])